"""StubHeaderGenerator: clang-tidy를 위한 가짜 헤더(stub) 생성기.

소스 파일의 #include를 분석하여 stubs/ 폴더에 빈 템플릿 헤더를 생성한다.
"""

import logging
import re
import shutil
from pathlib import Path

from mider.config.settings_loader import get_stub_extra_types

logger = logging.getLogger(__name__)

# " " 쌍따옴표 및 < > 꺾쇠 괄호 모두 추출 대상
_INCLUDE_PATTERN = re.compile(r'^\s*#\s*include\s*[<"]([^>"]+\.h)[>"]')

_STUB_TEMPLATE = """/* stub: {header_name} - auto-generated by mider StubHeaderGenerator */
/* DO NOT EDIT: This file is temporary and will be deleted after analysis. */
#ifndef {guard_macro}
#define {guard_macro}

/* --- 임베디드 C 공통 정수 타입 --- */
typedef unsigned char      UINT8;
typedef unsigned short     UINT16;
typedef unsigned int       UINT32;
typedef unsigned long long UINT64;
typedef signed char        INT8;
typedef signed short       INT16;
typedef signed int         INT32;
typedef long long          INT64;

/* --- 불리언 타입 --- */
typedef int BOOL;

/* --- 공통 매크로 --- */
#ifndef TRUE
#define TRUE  1
#endif
#ifndef FALSE
#define FALSE 0
#endif
#ifndef NULL
#define NULL  ((void*)0)
#endif

/* --- 프로젝트 커스텀 타입 (settings.yaml) --- */
{extra_types}

#endif /* {guard_macro} */
"""


class StubHeaderGenerator:
    """C 소스 파일의 #include를 파싱하여 임시 stub 헤더를 생성한다."""

    def __init__(self) -> None:
        self._extra_types = "\n".join(get_stub_extra_types())

    def generate(self, source_file: str, stubs_dir: Path) -> list[Path]:
        """소스 파일에서 #include "*.h" 를 파싱하고, stubs_dir 아래 stub 헤더를 생성한다.

        Args:
            source_file: 파싱할 C 소스 파일 경로
            stubs_dir: stub 헤더들이 생성될 디렉토리 경로

        Returns:
            생성된 stub 파일 경로 목록
        """
        source_path = Path(source_file)
        if not source_path.exists():
            return []

        try:
            content = source_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            try:
                content = source_path.read_text(encoding="cp949")
            except Exception as e:
                logger.warning(f"인코딩 에러로 파일 읽기 실패: {source_file} - {e}")
                return []
        
        headers = self._parse_includes(content)
        if not headers:
            return []

        # stubs 디렉토리 생성 (존재하면 무시)
        stubs_dir.mkdir(parents=True, exist_ok=True)
        
        generated_files = []
        for header in headers:
            try:
                stub_path = self._create_stub(header, stubs_dir)
                generated_files.append(stub_path)
            except Exception as e:
                logger.warning(f"stub 생성 실패: {header} - {e}")
                
        if generated_files:
            logger.info(f"Stub 헤더 생성 완료: {stubs_dir} 내 {len(generated_files)}개 파일")
            
        return generated_files

    def cleanup(self, stubs_dir: Path) -> None:
        """stubs_dir 디렉토리 전체를 삭제한다.

        Args:
            stubs_dir: 삭제할 stubs 디렉토리
        """
        if stubs_dir.exists() and stubs_dir.is_dir():
            try:
                shutil.rmtree(stubs_dir)
                logger.info(f"Stub 디렉토리 삭제 완료: {stubs_dir}")
            except Exception as e:
                logger.warning(f"Stub 디렉토리 삭제 실패: {stubs_dir} - {e}")

    def _parse_includes(self, content: str) -> list[str]:
        """소스 파일 본문에서 #include "..." 형식의 헤더 이름을 추출한다.

        중복은 제거된다.

        Args:
            content: C 소스 파일 내용

        Returns:
            헤더 파일명 리스트 (e.g. ["common.h", "api.h"])
        """
        headers = set()
        for line in content.splitlines():
            match = _INCLUDE_PATTERN.match(line)
            if match:
                headers.add(match.group(1))
        
        return sorted(list(headers))

    def _create_stub(self, header_name: str, stubs_dir: Path) -> Path:
        """stub 헤더 파일을 생성한다.

        헤더가 서브 경로를 갖는 경우(e.g. util/types.h) 서브 디렉토리를 알아서 생성한다.

        Args:
            header_name: 헤더 상대 경로 (e.g. "common.h")
            stubs_dir: 베이스 stubs 경로

        Returns:
            생성된 stub 파일의 경로
        """
        stub_path = stubs_dir / header_name
        stub_path.parent.mkdir(parents=True, exist_ok=True)

        guard_macro = f"STUB_{header_name.replace('/', '_').replace('.', '_').upper()}"
        
        content = _STUB_TEMPLATE.format(
            header_name=header_name,
            guard_macro=guard_macro,
            extra_types=self._extra_types
        )
        
        stub_path.write_text(content, encoding="utf-8")
        return stub_path
