"""StubHeaderGenerator: clang-tidy를 위한 헤더 resolver + stub 생성기.

소스의 #include를 파싱하여:
1) 실제 헤더가 근방에 있으면 그 디렉토리를 include path로 수집한다.
2) 찾지 못한 헤더와 시스템 헤더는 기존처럼 빈 stub을 생성한다.

실제 헤더가 참조된 경우 clang-tidy의 AST가 실제 typedef/struct로 완성되어
sizeof/struct field 관련 진단의 정확도가 크게 향상된다.
"""

import logging
import os
import re
import shutil
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path

from mider.config.settings_loader import get_stub_extra_types

logger = logging.getLogger(__name__)

# " " user-헤더와 < > system-헤더를 분리 캡처
_INCLUDE_PATTERN = re.compile(
    r'^\s*#\s*include\s*(?P<open>[<"])(?P<name>[^>"]+\.h)[>"]'
)

_STUB_TEMPLATE = """/* stub: {header_name} - auto-generated by mider StubHeaderGenerator */
/* DO NOT EDIT: This file is temporary and will be deleted after analysis. */
#ifndef {guard_macro}
#define {guard_macro}

/* --- 임베디드 C 공통 정수 타입 --- */
typedef unsigned char      UINT8;
typedef unsigned short     UINT16;
typedef unsigned int       UINT32;
typedef unsigned long long UINT64;
typedef signed char        INT8;
typedef signed short       INT16;
typedef signed int         INT32;
typedef long long          INT64;

/* --- 불리언 타입 --- */
typedef int BOOL;

/* --- 공통 매크로 --- */
#ifndef TRUE
#define TRUE  1
#endif
#ifndef FALSE
#define FALSE 0
#endif
#ifndef NULL
#define NULL  ((void*)0)
#endif

/* --- 프로젝트 커스텀 타입 (settings.yaml) --- */
{extra_types}

#endif /* {guard_macro} */
"""


@dataclass
class ResolveResult:
    """헤더 해석 결과.

    Attributes:
        real_include_dirs: -I 플래그에 추가할 실제 헤더가 위치한 디렉토리 목록 (case-insensitive dedupe).
        stub_files: 생성된 stub 파일 경로 목록.
        resolved_map: 헤더명 -> 실제 경로 매핑 (로그/디버그용).
        unresolved: stub으로 대체된 헤더 이름 목록.
    """

    real_include_dirs: list[Path] = field(default_factory=list)
    stub_files: list[Path] = field(default_factory=list)
    resolved_map: dict[str, Path] = field(default_factory=dict)
    unresolved: list[str] = field(default_factory=list)


class StubHeaderGenerator:
    """C 소스의 #include를 실제 헤더 우선으로 해결하고, 미해결 항목만 stub을 생성한다."""

    def __init__(self) -> None:
        self._extra_types = "\n".join(get_stub_extra_types())

    def resolve(
        self,
        source_file: str,
        stubs_dir: Path,
        *,
        search_anchor: Path | None = None,
        max_walk_up: int = 5,
        max_recursion: int = 3,
    ) -> ResolveResult:
        """소스의 #include를 실제 헤더 우선으로 해결한다.

        Args:
            source_file: 분석 대상 C/Pro*C 소스 파일 경로 (내용을 파싱한다).
            stubs_dir: 미해결 헤더용 stub이 생성될 디렉토리.
            search_anchor: walk-up 시작 디렉토리. None이면 source_file의 부모 사용.
                           Pro*C처럼 tmp 파일을 분석할 때 원본 경로를 지정한다.
            max_walk_up: 상위 디렉토리 탐색 최대 단계 수.
            max_recursion: 실제 헤더 내부 #include를 따라 들어가는 최대 깊이.

        Returns:
            ResolveResult
        """
        result = ResolveResult()
        source_path = Path(source_file)
        if not source_path.exists():
            return result

        content = self._read_text(source_path)
        if content is None:
            return result

        includes = self._parse_includes(content)
        if not includes:
            return result

        anchor = search_anchor if search_anchor is not None else source_path.parent
        visited: set[str] = set()  # 재귀 중복 차단 (absolute path, case-insensitive)
        real_dirs_key: set[str] = set()  # real_include_dirs case-insensitive dedupe

        # BFS — (header_name, is_system, depth)
        queue: deque[tuple[str, bool, int]] = deque(
            (name, is_sys, 0) for name, is_sys in includes
        )
        stubbed_names: set[str] = set()  # 중복 stub 생성 방지
        stubbed_system_count = 0  # 로그용

        while queue:
            header_name, is_system, depth = queue.popleft()

            if is_system:
                # 시스템 헤더는 항상 stub — 실제 경로 탐색 생략
                if header_name not in stubbed_names:
                    self._create_stub_safe(header_name, stubs_dir, result, stubbed_names)
                    stubbed_system_count += 1
                continue

            real_path = self._find_real_header(header_name, anchor, max_walk_up)
            if real_path is None:
                if header_name not in stubbed_names:
                    self._create_stub_safe(header_name, stubs_dir, result, stubbed_names)
                    result.unresolved.append(header_name)
                continue

            key = self._case_key(real_path)
            if key in visited:
                continue
            visited.add(key)

            result.resolved_map[header_name] = real_path

            dir_key = self._case_key(real_path.parent)
            if dir_key not in real_dirs_key:
                real_dirs_key.add(dir_key)
                result.real_include_dirs.append(real_path.parent)

            # 전이 #include: 깊이 상한 내에서만 큐에 넣는다
            if depth < max_recursion:
                sub_content = self._read_text(real_path)
                if sub_content:
                    for sub_name, sub_is_sys in self._parse_includes(sub_content):
                        queue.append((sub_name, sub_is_sys, depth + 1))

        logger.info(
            "Include resolution: %d real (from %d dirs), %d stubbed "
            "(unresolved=%d, system=%d)",
            len(result.resolved_map),
            len(result.real_include_dirs),
            len(result.stub_files),
            len(result.unresolved),
            stubbed_system_count,
        )
        for header_name, path in result.resolved_map.items():
            logger.debug("  real: %s -> %s", header_name, path)
        for name in result.unresolved:
            logger.debug("  stub: %s (not found)", name)

        return result

    def generate(self, source_file: str, stubs_dir: Path) -> list[Path]:
        """하위 호환: 모든 #include에 대해 무조건 stub을 생성한다.

        내부적으로 resolve()를 max_walk_up=0으로 호출한다 (실경로 탐색 비활성).
        """
        result = self.resolve(source_file, stubs_dir, max_walk_up=0)
        return result.stub_files

    def cleanup(self, stubs_dir: Path) -> None:
        """stubs_dir 디렉토리 전체를 삭제한다."""
        if stubs_dir.exists() and stubs_dir.is_dir():
            try:
                shutil.rmtree(stubs_dir)
                logger.info(f"Stub 디렉토리 삭제 완료: {stubs_dir}")
            except Exception as e:
                logger.warning(f"Stub 디렉토리 삭제 실패: {stubs_dir} - {e}")

    # ---- 내부 ----

    @staticmethod
    def _read_text(path: Path) -> str | None:
        """UTF-8 → CP949 순으로 텍스트 읽기 시도."""
        try:
            return path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            try:
                return path.read_text(encoding="cp949")
            except Exception as e:
                logger.warning(f"인코딩 에러로 파일 읽기 실패: {path} - {e}")
                return None
        except Exception as e:
            logger.warning(f"파일 읽기 실패: {path} - {e}")
            return None

    def _parse_includes(self, content: str) -> list[tuple[str, bool]]:
        """#include 추출. 중복 제거, 발생 순서 보존.

        Returns:
            (header_name, is_system) 튜플 리스트. is_system은 <...> 형식 여부.
        """
        seen: set[tuple[str, bool]] = set()
        ordered: list[tuple[str, bool]] = []
        for line in content.splitlines():
            match = _INCLUDE_PATTERN.match(line)
            if not match:
                continue
            name = match.group("name")
            is_system = match.group("open") == "<"
            key = (name, is_system)
            if key in seen:
                continue
            seen.add(key)
            ordered.append(key)
        return ordered

    @staticmethod
    def _find_real_header(
        header_name: str,
        start_dir: Path,
        max_walk_up: int,
    ) -> Path | None:
        """start_dir에서 최대 max_walk_up 단계까지 walk-up하며 헤더를 찾는다.

        헤더명에 서브 경로(예: "util/types.h")가 있으면 각 단계 디렉토리 기준으로 결합한다.
        """
        if max_walk_up < 0:
            return None
        current = start_dir
        for _ in range(max_walk_up + 1):  # 0-th step = start_dir 자신
            candidate = current / header_name
            if candidate.exists() and candidate.is_file():
                return candidate.resolve()
            if current.parent == current:
                break
            current = current.parent
        return None

    def _create_stub_safe(
        self,
        header_name: str,
        stubs_dir: Path,
        result: ResolveResult,
        stubbed_names: set[str],
    ) -> None:
        try:
            stubs_dir.mkdir(parents=True, exist_ok=True)
            stub_path = self._create_stub(header_name, stubs_dir)
            result.stub_files.append(stub_path)
            stubbed_names.add(header_name)
        except Exception as e:
            logger.warning(f"stub 생성 실패: {header_name} - {e}")

    def _create_stub(self, header_name: str, stubs_dir: Path) -> Path:
        """stub 헤더 파일을 생성한다.

        헤더가 서브 경로를 갖는 경우(e.g. util/types.h) 서브 디렉토리를 알아서 생성한다.
        """
        stub_path = stubs_dir / header_name
        stub_path.parent.mkdir(parents=True, exist_ok=True)

        guard_macro = f"STUB_{header_name.replace('/', '_').replace('.', '_').upper()}"

        content = _STUB_TEMPLATE.format(
            header_name=header_name,
            guard_macro=guard_macro,
            extra_types=self._extra_types,
        )

        stub_path.write_text(content, encoding="utf-8")
        return stub_path

    @staticmethod
    def _case_key(path: Path) -> str:
        """Windows는 case-insensitive FS이므로 lower()로 정규화."""
        s = str(path)
        return s.lower() if os.name == "nt" else s

