export default [
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        // browser globals
        window: "readonly",
        document: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        alert: "readonly",
        confirm: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        XMLHttpRequest: "readonly",
        fetch: "readonly",
        FormData: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        Promise: "readonly",
        Map: "readonly",
        Set: "readonly",
        Symbol: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Date: "readonly",
        RegExp: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        Number: "readonly",
        Boolean: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        isFinite: "readonly",
        encodeURIComponent: "readonly",
        decodeURIComponent: "readonly",
        encodeURI: "readonly",
        decodeURI: "readonly",
        btoa: "readonly",
        atob: "readonly",
        // WebSquare/Proframe globals
        WebSquare: "readonly",
        ngmf: "readonly",
        ngmv: "readonly",
        scwin: "readonly",
        scvar: "readonly",
        GLV: "readonly",
        GLD: "readonly",
        afxf: "readonly",
        promise: "readonly",
      },
    },
    rules: {
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-fallthrough": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "no-cond-assign": "error",
      "no-constant-condition": "error",
      "no-unsafe-finally": "error",
      "no-loss-of-precision": "error",
      "no-sparse-arrays": "error",
      "array-callback-return": "error",
      "no-redeclare": ["error", { builtinGlobals: true }],
      "no-shadow": "warn",
      "no-return-assign": "error",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-throw-literal": "error",
    },
  },
];
